version: '3.8'

services:
  backend:
    build: ./backend
    container_name: ynab_backend
    restart: always
    environment:
      - DEBUG=False
      - SECRET_KEY=troque-isso-por-algo-seguro-no-servidor
    volumes:
      - sqlite_data:/app
    expose:
      - "8000"

  frontend:
    build: ./Ynab
    container_name: ynab_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  sqlite_data:
