services:
  - type: web
    name: ynab-backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn ynab_backend.wsgi:application"
    rootDir: backend
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false # Você preencherá isso com o valor do Supabase no painel do Render
