# Generated by Django 5.2.13 on 2026-06-05 19:27

from django.db import migrations
from django.core.management import call_command


def trigger_migration(apps, schema_editor):
    # Runs the subaccount migration script on deploy
    call_command('migrate_subaccounts')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_account_bank_domain'),
    ]

    operations = [
        migrations.RunPython(trigger_migration, reverse_code=migrations.RunPython.noop),
    ]
