# Generated by Django 5.2.13 on 2026-06-05 20:49

from django.db import migrations
from django.core.management import call_command

def trigger_currency_fix(apps, schema_editor):
    call_command('fix_currency_mess')

class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_run_subaccount_migration'),
    ]

    operations = [
        migrations.RunPython(trigger_currency_fix, elidable=True),
    ]
