# Generated by Django 5.2.13 on 2026-06-05 21:04

from django.db import migrations
from decimal import Decimal

def restore_brl_deep_math(apps, schema_editor):
    Category = apps.get_model('core', 'Category')
    MonthlyBudget = apps.get_model('core', 'MonthlyBudget')
    Transaction = apps.get_model('core', 'Transaction')
    CategoryGoal = apps.get_model('core', 'CategoryGoal')
    
    factor = Decimal('6.000857')
    
    # 1. Obter todas as categorias BRL
    brl_categories = Category.objects.filter(currency='BRL')
    
    for category in brl_categories:
        # Apenas reverte a matemática se o valor for menor que a média histórica BRL normal e name contiver Nubank
        if "Nubank" in category.name:
            is_scaled = False
            
            if category.target_value > 0 and category.target_value < Decimal('50.00'):
                category.target_value = (category.target_value * factor).quantize(Decimal('0.01'))
                is_scaled = True
            if category.ceiling_value > 0 and category.ceiling_value < Decimal('50.00'):
                category.ceiling_value = (category.ceiling_value * factor).quantize(Decimal('0.01'))
                is_scaled = True
                
            if is_scaled:
                category.save()
            
            # 2. Orçamentos Mensais (MonthlyBudget)
            budgets = MonthlyBudget.objects.filter(category=category)
            for budget in budgets:
                if budget.amount > 0 and budget.amount < Decimal('50.00'):
                    budget.amount = (budget.amount * factor).quantize(Decimal('0.01'))
                    budget.save()
                    
            # 3. Transações (Transaction)
            transactions = Transaction.objects.filter(category=category)
            for transaction in transactions:
                if transaction.amount > 0 and transaction.amount < Decimal('500.00'):
                    transaction.amount = (transaction.amount * factor).quantize(Decimal('0.01'))
                    transaction.save()
                    
            # 4. Metas da Categoria (CategoryGoal)
            try:
                goal = CategoryGoal.objects.get(category=category)
                if goal.amount > 0 and goal.amount < Decimal('50.00'):
                    goal.amount = (goal.amount * factor).quantize(Decimal('0.01'))
                    goal.save()
            except Exception:
                pass

class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_run_currency_fix'),
        ('core', '0064_account_bank_domain'),
    ]

    operations = [
        migrations.RunPython(restore_brl_deep_math, elidable=True),
    ]
