# Generated by Django 6.0.4 on 2026-04-25 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_account_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='budgeted_amount',
            new_name='assigned_amount',
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.category'),
        ),
    ]
