# Generated by Django 6.0.4 on 2026-05-03 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_account_icon_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transfer_group',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
