# Generated by Django 6.0.4 on 2026-05-04 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_distributiontemplate_distributiontemplateitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_applied_to_balance',
            field=models.BooleanField(default=False),
        ),
    ]
