# Generated by Django 6.0.4 on 2026-05-04 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_transaction_is_applied_to_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('realized', 'Efetivada')], default='realized', max_length=10),
        ),
    ]
