# Generated by Django 6.0.4 on 2026-04-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_category_assigned_amount_monthlybudget'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='currency',
            field=models.CharField(default='EUR', max_length=3),
        ),
    ]
