# Generated by Django 6.0.4 on 2026-05-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_userprofile_language_userprofile_preferred_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='icon_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
