# Generated by Django 6.0.4 on 2026-05-03 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_transaction_transfer_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='currency',
            field=models.CharField(default='EUR', max_length=3),
        ),
        migrations.AlterField(
            model_name='goal',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
