# Generated by Django 6.0.4 on 2026-05-09 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='ceiling',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
