# Generated by Django 6.0.4 on 2026-05-11 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_create_initial_balances_for_master_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='exclude_from_totals',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelTable(
            name='account',
            table='core_account',
        ),
        migrations.AlterModelTable(
            name='category',
            table='core_category',
        ),
        migrations.AlterModelTable(
            name='debt',
            table='core_debt',
        ),
        migrations.AlterModelTable(
            name='debtpayment',
            table='core_debtpayment',
        ),
        migrations.AlterModelTable(
            name='distributiontemplate',
            table='core_distributiontemplate',
        ),
        migrations.AlterModelTable(
            name='distributiontemplateitem',
            table='core_distributiontemplateitem',
        ),
        migrations.AlterModelTable(
            name='goal',
            table='core_goal',
        ),
        migrations.AlterModelTable(
            name='monthlybudget',
            table='core_monthlybudget',
        ),
        migrations.AlterModelTable(
            name='transaction',
            table='core_transaction',
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='core_userprofile',
        ),
    ]
