# Generated by Django 6.0.4 on 2026-05-13 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_supportticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closing_day', models.PositiveSmallIntegerField()),
                ('due_day', models.PositiveSmallIntegerField()),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_card_config', to='core.account')),
            ],
            options={
                'db_table': 'core_creditcard',
            },
        ),
        migrations.CreateModel(
            name='CreditCardBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('is_closed', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('credit_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='core.creditcard')),
            ],
            options={
                'db_table': 'core_creditcardbill',
                'unique_together': {('credit_card', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='CreditCardTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('installment_count', models.PositiveSmallIntegerField(default=1)),
                ('original_currency', models.CharField(default='BRL', max_length=3)),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=1.0, max_digits=10)),
                ('iof_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_card_transactions', to='core.category')),
                ('credit_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matrix_transactions', to='core.creditcard')),
            ],
            options={
                'db_table': 'core_creditcardtransaction',
            },
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('posted', 'Lançada'), ('paid', 'Paga'), ('anticipated', 'Antecipada')], default='pending', max_length=20)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='core.creditcardbill')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='core.creditcardtransaction')),
            ],
            options={
                'db_table': 'core_installment',
                'unique_together': {('transaction', 'number')},
            },
        ),
    ]
