# Generated by Django 6.0.4 on 2026-05-17 13:03

import django.db.models.deletion
import finance.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_creditcard_creditcardbill_creditcardtransaction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionInbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=finance.models.transaction_inbox_upload_path)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('ready', 'Pronto'), ('failed', 'Falhou')], default='pending', max_length=20)),
                ('ai_suggestions', models.JSONField(blank=True, default=dict, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_inbox_items', to=settings.AUTH_USER_MODEL)),
                ('validated_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbox_sources', to='core.transaction')),
            ],
            options={
                'db_table': 'core_transactioninbox',
            },
        ),
    ]
