# Generated by Django 5.2.13 on 2026-05-18 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_account_id_alter_category_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='last_reconciled',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='cleared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reconciled',
            field=models.BooleanField(default=False),
        ),
    ]
