# Generated by Django 5.2.13 on 2026-05-20 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_account_last_reconciled_transaction_cleared_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_recurrence_exception',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='recurring_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_children', to='core.transaction'),
        ),
    ]
