# Generated by Django on 2026-05-20

from django.db import migrations

def link_legacy_recurring_transactions(apps, schema_editor):
    Transaction = apps.get_model('core', 'Transaction')
    
    # Busca todos os templates recorrentes originais
    templates = Transaction.objects.filter(is_recurring=True)
    
    for t in templates:
        # Busca todas as transações que parecem filhas desse template, mas não estão vinculadas
        children = Transaction.objects.filter(
            account=t.account,
            description=t.description,
            amount=t.amount,
            is_recurring=False,
            recurring_parent__isnull=True
        )
        # Vincula-as ao pai
        children.update(recurring_parent=t)

def reverse_linking(apps, schema_editor):
    pass # Migração irreversível, não precisamos desvincular

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_transaction_is_recurrence_exception_and_more'),
    ]

    operations = [
        migrations.RunPython(link_legacy_recurring_transactions, reverse_linking),
    ]
