# Generated by Django 5.2.13 on 2026-05-20 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_link_legacy_recurring'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebtCharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debt_charges', to='core.account')),
                ('debt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='core.debt')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debt_charge', to='core.transaction')),
            ],
            options={
                'db_table': 'core_debtcharge',
            },
        ),
    ]
