# Generated by Django 6.0.4 on 2026-05-18 20:00

from django.db import migrations

def enable_rls_and_policies(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return

    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SELECT 1 FROM pg_roles WHERE rolname = 'authenticator'")
        if not cursor.fetchone():
            return

        queries = [
            # Enable RLS on all tables
            "ALTER TABLE core_userprofile ENABLE ROW LEVEL SECURITY;",
            "ALTER TABLE core_supportticket ENABLE ROW LEVEL SECURITY;",
            "ALTER TABLE core_account ENABLE ROW LEVEL SECURITY;",
            "ALTER TABLE core_category ENABLE ROW LEVEL SECURITY;",
            "ALTER TABLE core_payee ENABLE ROW LEVEL SECURITY;",
            "ALTER TABLE core_monthlybudget ENABLE ROW LEVEL SECURITY;",
            "ALTER TABLE core_transaction ENABLE ROW LEVEL SECURITY;",
            "ALTER TABLE core_goal ENABLE ROW LEVEL SECURITY;",
            "ALTER TABLE core_distributiontemplate ENABLE ROW LEVEL SECURITY;",
            "ALTER TABLE core_distributiontemplateitem ENABLE ROW LEVEL SECURITY;",
            "ALTER TABLE core_debt ENABLE ROW LEVEL SECURITY;",
            "ALTER TABLE core_debtpayment ENABLE ROW LEVEL SECURITY;",
            "ALTER TABLE core_debtcharge ENABLE ROW LEVEL SECURITY;",
            "ALTER TABLE core_creditcard ENABLE ROW LEVEL SECURITY;",
            "ALTER TABLE core_creditcardbill ENABLE ROW LEVEL SECURITY;",
            "ALTER TABLE core_creditcardtransaction ENABLE ROW LEVEL SECURITY;",
            "ALTER TABLE core_installment ENABLE ROW LEVEL SECURITY;",
            "ALTER TABLE core_transactioninbox ENABLE ROW LEVEL SECURITY;",
            "ALTER TABLE core_categorygoal ENABLE ROW LEVEL SECURITY;",
            "ALTER TABLE core_transactionrule ENABLE ROW LEVEL SECURITY;",

            # Baseline Policies for tables with direct user_id
            "CREATE POLICY \"Users can only access their own userprofile\" ON core_userprofile USING (CAST(user_id AS TEXT) = auth.uid()::text);",
            "CREATE POLICY \"Users can only access their own supportticket\" ON core_supportticket USING (CAST(user_id AS TEXT) = auth.uid()::text);",
            "CREATE POLICY \"Users can only access their own account\" ON core_account USING (CAST(user_id AS TEXT) = auth.uid()::text);",
            "CREATE POLICY \"Users can only access their own category\" ON core_category USING (CAST(user_id AS TEXT) = auth.uid()::text);",
            "CREATE POLICY \"Users can only access their own payee\" ON core_payee USING (CAST(user_id AS TEXT) = auth.uid()::text);",
            "CREATE POLICY \"Users can only access their own goal\" ON core_goal USING (CAST(user_id AS TEXT) = auth.uid()::text);",
            "CREATE POLICY \"Users can only access their own distributiontemplate\" ON core_distributiontemplate USING (CAST(user_id AS TEXT) = auth.uid()::text);",
            "CREATE POLICY \"Users can only access their own debt\" ON core_debt USING (CAST(user_id AS TEXT) = auth.uid()::text);",
            "CREATE POLICY \"Users can only access their own transactioninbox\" ON core_transactioninbox USING (CAST(user_id AS TEXT) = auth.uid()::text);",
            "CREATE POLICY \"Users can only access their own transactionrule\" ON core_transactionrule USING (CAST(user_id AS TEXT) = auth.uid()::text);",

            # Nested Policies for related tables
            "CREATE POLICY \"Users can only access their own monthlybudget\" ON core_monthlybudget USING (EXISTS (SELECT 1 FROM core_category WHERE core_category.id = core_monthlybudget.category_id AND CAST(core_category.user_id AS TEXT) = auth.uid()::text));",
            "CREATE POLICY \"Users can only access their own transaction\" ON core_transaction USING (EXISTS (SELECT 1 FROM core_account WHERE core_account.id = core_transaction.account_id AND CAST(core_account.user_id AS TEXT) = auth.uid()::text));",
            "CREATE POLICY \"Users can only access their own distributiontemplateitem\" ON core_distributiontemplateitem USING (EXISTS (SELECT 1 FROM core_distributiontemplate WHERE core_distributiontemplate.id = core_distributiontemplateitem.template_id AND CAST(core_distributiontemplate.user_id AS TEXT) = auth.uid()::text));",
            "CREATE POLICY \"Users can only access their own debtpayment\" ON core_debtpayment USING (EXISTS (SELECT 1 FROM core_debt WHERE core_debt.id = core_debtpayment.debt_id AND CAST(core_debt.user_id AS TEXT) = auth.uid()::text));",
            "CREATE POLICY \"Users can only access their own debtcharge\" ON core_debtcharge USING (EXISTS (SELECT 1 FROM core_debt WHERE core_debt.id = core_debtcharge.debt_id AND CAST(core_debt.user_id AS TEXT) = auth.uid()::text));",
            "CREATE POLICY \"Users can only access their own creditcard\" ON core_creditcard USING (EXISTS (SELECT 1 FROM core_account WHERE core_account.id = core_creditcard.account_id AND CAST(core_account.user_id AS TEXT) = auth.uid()::text));",
            "CREATE POLICY \"Users can only access their own creditcardbill\" ON core_creditcardbill USING (EXISTS (SELECT 1 FROM core_creditcard JOIN core_account ON core_creditcard.account_id = core_account.id WHERE core_creditcard.id = core_creditcardbill.credit_card_id AND CAST(core_account.user_id AS TEXT) = auth.uid()::text));",
            "CREATE POLICY \"Users can only access their own creditcardtransaction\" ON core_creditcardtransaction USING (EXISTS (SELECT 1 FROM core_creditcard JOIN core_account ON core_creditcard.account_id = core_account.id WHERE core_creditcard.id = core_creditcardtransaction.credit_card_id AND CAST(core_account.user_id AS TEXT) = auth.uid()::text));",
            "CREATE POLICY \"Users can only access their own installment\" ON core_installment USING (EXISTS (SELECT 1 FROM core_creditcardtransaction JOIN core_creditcard ON core_creditcardtransaction.credit_card_id = core_creditcard.id JOIN core_account ON core_creditcard.account_id = core_account.id WHERE core_creditcardtransaction.id = core_installment.transaction_id AND CAST(core_account.user_id AS TEXT) = auth.uid()::text));",
            "CREATE POLICY \"Users can only access their own categorygoal\" ON core_categorygoal USING (EXISTS (SELECT 1 FROM core_category WHERE core_category.id = core_categorygoal.category_id AND CAST(core_category.user_id AS TEXT) = auth.uid()::text));",
        ]
        for query in queries:
            cursor.execute(query)

def disable_rls_and_policies(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return

    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SELECT 1 FROM pg_roles WHERE rolname = 'authenticator'")
        if not cursor.fetchone():
            return

        queries = [
            "DROP POLICY IF EXISTS \"Users can only access their own userprofile\" ON core_userprofile;",
            "DROP POLICY IF EXISTS \"Users can only access their own supportticket\" ON core_supportticket;",
            "DROP POLICY IF EXISTS \"Users can only access their own account\" ON core_account;",
            "DROP POLICY IF EXISTS \"Users can only access their own category\" ON core_category;",
            "DROP POLICY IF EXISTS \"Users can only access their own payee\" ON core_payee;",
            "DROP POLICY IF EXISTS \"Users can only access their own goal\" ON core_goal;",
            "DROP POLICY IF EXISTS \"Users can only access their own distributiontemplate\" ON core_distributiontemplate;",
            "DROP POLICY IF EXISTS \"Users can only access their own debt\" ON core_debt;",
            "DROP POLICY IF EXISTS \"Users can only access their own transactioninbox\" ON core_transactioninbox;",
            "DROP POLICY IF EXISTS \"Users can only access their own transactionrule\" ON core_transactionrule;",
            "DROP POLICY IF EXISTS \"Users can only access their own monthlybudget\" ON core_monthlybudget;",
            "DROP POLICY IF EXISTS \"Users can only access their own transaction\" ON core_transaction;",
            "DROP POLICY IF EXISTS \"Users can only access their own distributiontemplateitem\" ON core_distributiontemplateitem;",
            "DROP POLICY IF EXISTS \"Users can only access their own debtpayment\" ON core_debtpayment;",
            "DROP POLICY IF EXISTS \"Users can only access their own debtcharge\" ON core_debtcharge;",
            "DROP POLICY IF EXISTS \"Users can only access their own creditcard\" ON core_creditcard;",
            "DROP POLICY IF EXISTS \"Users can only access their own creditcardbill\" ON core_creditcardbill;",
            "DROP POLICY IF EXISTS \"Users can only access their own creditcardtransaction\" ON core_creditcardtransaction;",
            "DROP POLICY IF EXISTS \"Users can only access their own installment\" ON core_installment;",
            "DROP POLICY IF EXISTS \"Users can only access their own categorygoal\" ON core_categorygoal;",

            "ALTER TABLE core_userprofile DISABLE ROW LEVEL SECURITY;",
            "ALTER TABLE core_supportticket DISABLE ROW LEVEL SECURITY;",
            "ALTER TABLE core_account DISABLE ROW LEVEL SECURITY;",
            "ALTER TABLE core_category DISABLE ROW LEVEL SECURITY;",
            "ALTER TABLE core_payee DISABLE ROW LEVEL SECURITY;",
            "ALTER TABLE core_monthlybudget DISABLE ROW LEVEL SECURITY;",
            "ALTER TABLE core_transaction DISABLE ROW LEVEL SECURITY;",
            "ALTER TABLE core_goal DISABLE ROW LEVEL SECURITY;",
            "ALTER TABLE core_distributiontemplate DISABLE ROW LEVEL SECURITY;",
            "ALTER TABLE core_distributiontemplateitem DISABLE ROW LEVEL SECURITY;",
            "ALTER TABLE core_debt DISABLE ROW LEVEL SECURITY;",
            "ALTER TABLE core_debtpayment DISABLE ROW LEVEL SECURITY;",
            "ALTER TABLE core_debtcharge DISABLE ROW LEVEL SECURITY;",
            "ALTER TABLE core_creditcard DISABLE ROW LEVEL SECURITY;",
            "ALTER TABLE core_creditcardbill DISABLE ROW LEVEL SECURITY;",
            "ALTER TABLE core_creditcardtransaction DISABLE ROW LEVEL SECURITY;",
            "ALTER TABLE core_installment DISABLE ROW LEVEL SECURITY;",
            "ALTER TABLE core_transactioninbox DISABLE ROW LEVEL SECURITY;",
            "ALTER TABLE core_categorygoal DISABLE ROW LEVEL SECURITY;",
            "ALTER TABLE core_transactionrule DISABLE ROW LEVEL SECURITY;",
        ]
        for query in queries:
            cursor.execute(query)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_add_debt_charge_model'),
    ]

    operations = [
        migrations.RunPython(enable_rls_and_policies, reverse_code=disable_rls_and_policies),
    ]
