# Generated by Django 5.2.13 on 2026-05-22 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_add_debt_charge_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='hidden_sidebar_items',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
