# Generated by Django 6.0.4 on 2026-05-18 20:20

from django.db import migrations

def migrate_credit_to_credit_card(apps, schema_editor):
    Account = apps.get_model('core', 'Account')
    Account.objects.filter(account_type='credit').update(account_type='credit_card')

def migrate_credit_card_to_credit(apps, schema_editor):
    Account = apps.get_model('core', 'Account')
    Account.objects.filter(account_type='credit_card').update(account_type='credit')

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_enable_rls_and_policies'),
    ]

    operations = [
        migrations.RunPython(migrate_credit_to_credit_card, reverse_code=migrate_credit_card_to_credit),
    ]
