# Generated by Django 5.2.13 on 2026-05-22 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_dailycdirate_investmentactivity_cdi_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentasset',
            name='asset_type',
            field=models.CharField(choices=[('STOCK', 'Stock'), ('FIXED_INCOME', 'Fixed Income'), ('TREASURY', 'Tesouro Direto'), ('FII', 'FII'), ('ETF', 'ETF'), ('CRYPTO', 'Crypto')], max_length=50),
        ),
    ]
