# Generated by Django 5.2.13 on 2026-05-22 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_investmentasset_asset_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentasset',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investmentasset',
            name='indexer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='investmentasset',
            name='issuer',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='investmentasset',
            name='liquidity_daily',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='investmentasset',
            name='rate_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='investmentasset',
            name='title_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
