# Generated by Django 5.2.13 on 2026-05-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_investmentasset_due_date_investmentasset_indexer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentactivity',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investmentasset',
            name='asset_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='investmentasset',
            name='market_country',
            field=models.CharField(default='BR', max_length=2),
        ),
        migrations.AlterField(
            model_name='investmentasset',
            name='asset_type',
            field=models.CharField(choices=[('STOCK', 'Stock'), ('FIXED_INCOME', 'Fixed Income'), ('TREASURY', 'Tesouro Direto'), ('FII', 'FIIs'), ('ETF', 'ETFs'), ('CRYPTO', 'Crypto'), ('BOND', 'Bonds'), ('MUTUAL_FUND', 'Fundo de Investimento')], max_length=50),
        ),
    ]
