# Generated by Django 5.2.13 on 2026-05-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_investmentactivity_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pinned_countries',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
