# Generated by Django 6.0.4 on 2026-05-23 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_transaction_credit_card_bill_alter_account_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='brand',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
