# Generated by Django 6.0.4 on 2026-05-23 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_creditcard_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcardtransaction',
            name='expense_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_card_expenses', to='core.account'),
        ),
    ]
