# Generated by Django 6.0.4 on 2026-05-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_creditcardtransaction_expense_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='country_of_issue',
            field=models.CharField(choices=[('BR', 'Brasil'), ('PT', 'Portugal')], default='BR', max_length=2),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='revolving_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='settlement_mode',
            field=models.CharField(choices=[('FULL_REIMBURSEMENT', '100% de Reembolso (Fim do Mês)'), ('REVOLVING_CREDIT', 'Crédito Rotativo (Pagamento Parcial)'), ('FRACTIONED', 'Pagamento Fracionado / Parcelamento')], default='FULL_REIMBURSEMENT', max_length=20),
        ),
    ]
