# Generated by Django 5.2.13 on 2026-05-29 12:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_account_reserved_credit_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='ceiling_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='category',
            name='target_type',
            field=models.CharField(choices=[('FIXED', 'Valor Fixo'), ('PERCENTAGE', 'Percentual da Receita')], default='FIXED', max_length=10),
        ),
        migrations.AddField(
            model_name='category',
            name='target_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
