# Generated by Django 6.0.4 on 2026-05-30 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_alter_account_id_alter_category_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcardtransaction',
            name='expense_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='credit_card_expenses', to='core.account'),
        ),
        migrations.AlterField(
            model_name='installment',
            name='subaccount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='installments', to='core.account'),
        ),
    ]
