# Generated by Django 5.2.13 on 2026-05-30 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_recalculate_reserved_credit_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='origin_subaccount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_debts', to='core.account'),
        ),
    ]
