# Generated by Django 6.0.4 on 2026-06-02 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_alter_account_id_alter_category_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='domain',
            field=models.CharField(blank=True, help_text='e.g., nubank.com.br, cgd.pt', max_length=255, null=True),
        ),
    ]
