# Generated by Django 6.0.4 on 2026-06-03 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_investmentasset_macro_category_alter_account_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='target_type',
            field=models.CharField(choices=[('NEEDED_FOR_SPENDING', 'Necessário para Gastos'), ('SAVINGS_BUILDER', 'Acumulador de Poupança'), ('FIXED', 'Valor Fixo'), ('PERCENTAGE', 'Percentual da Receita')], default='NEEDED_FOR_SPENDING', max_length=30),
        ),
    ]
