# Generated by Django 6.0.4 on 2026-06-03 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_alter_category_target_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='macro_rule',
            field=models.CharField(choices=[('NEEDS', 'Necessidades'), ('WANTS', 'Desejos'), ('SAVINGS', 'Poupança'), ('NONE', 'Nenhum')], default='NONE', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='needs_target_pct',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='savings_target_pct',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='wants_target_pct',
            field=models.IntegerField(default=30),
        ),
    ]
