# Generated by Django 5.2.13 on 2026-06-03 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_debt_origin_category_debt_origin_transaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trusteddevice',
            name='custom_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trusteddevice',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trusteddevice',
            name='last_used_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='trusteddevice',
            name='location_string',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trusteddevice',
            name='os_browser_info',
            field=models.CharField(default='Chrome on Windows', max_length=255),
        ),
    ]
