# Generated by Django 5.2.13 on 2026-06-04 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_trusteddevice_custom_name_trusteddevice_ip_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='is_recurrence_exception',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('realized', 'Efetivada'), ('scheduled', 'Agendada')], db_index=True, default='realized', max_length=10),
        ),
    ]
