# Generated by Django 5.2.13 on 2026-06-04 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_alter_transaction_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='is_mine',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='installment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('posted', 'Lançada'), ('paid', 'Paga'), ('anticipated', 'Antecipada')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='monthlybudget',
            name='month',
            field=models.PositiveSmallIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='monthlybudget',
            name='year',
            field=models.PositiveSmallIntegerField(db_index=True),
        ),
    ]
