# Generated by Django 6.0.4 on 2026-06-05 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_alter_account_id_alter_category_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributiontemplateitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.category'),
        ),
        migrations.AlterField(
            model_name='distributiontemplateitem',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.account'),
        ),
    ]
