# Generated by Django 6.0.4 on 2026-06-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_distributiontemplateitem_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='macro_allocation',
            field=models.CharField(choices=[('NEEDS', 'Necessidades (50%)'), ('WANTS', 'Desejos (30%)'), ('SAVINGS', 'Poupança/Investimentos (20%)'), ('NONE', 'Não Monitorado')], default='NONE', max_length=10),
        ),
    ]
