# Generated by Django 6.0.4 on 2026-06-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_category_macro_allocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='bank_domain',
            field=models.CharField(blank=True, help_text='e.g., nubank.com.br, millenniumbcp.pt', max_length=255, null=True),
        ),
    ]
