# Generated by Django 5.2.13 on 2026-06-05 19:58

from django.db import migrations
from decimal import Decimal


def restore_brl_values(apps, schema_editor):
    Category = apps.get_model('core', 'Category')
    MonthlyBudget = apps.get_model('core', 'MonthlyBudget')
    
    # 140.00 / 23.33 = 6.000857265323617
    rate = Decimal('6.000857265323617')
    
    # Filtrar categorias que contêm "Nubank" no nome (ou sub-contas BRL conhecidas)
    brl_categories = Category.objects.filter(name__icontains="Nubank")
    
    for cat in brl_categories:
        # Define a moeda como BRL
        cat.currency = 'BRL'
        
        # Restaura os valores se forem maiores que zero
        if cat.target_value and cat.target_value > 0:
            cat.target_value = round(cat.target_value * rate, 2)
            
        if cat.ceiling_value and cat.ceiling_value > 0:
            cat.ceiling_value = round(cat.ceiling_value * rate, 2)
            
        cat.save()
        
        # Restaura o orçamento mensal (MonthlyBudget)
        mbudgets = MonthlyBudget.objects.filter(category=cat)
        for mb in mbudgets:
            if mb.amount and mb.amount > 0:
                mb.amount = round(mb.amount * rate, 2)
                mb.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_category_currency_alter_account_id_alter_asset_id_and_more'),
    ]

    operations = [
        migrations.RunPython(restore_brl_values, reverse_code=migrations.RunPython.noop),
    ]
