# Generated by Django 5.2.13 on 2026-06-06 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_restore_brl_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditcardtransaction',
            name='expense_account',
        ),
        migrations.RemoveField(
            model_name='installment',
            name='subaccount',
        ),
        migrations.AlterField(
            model_name='creditcardtransaction',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_card_transactions', to='core.category'),
        ),
    ]
