# Generated by Django 6.0.4 on 2026-06-12 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_alter_account_account_type_alter_account_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debtpayment',
            name='debt',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='linked_debt',
        ),
        migrations.RemoveField(
            model_name='debtcharge',
            name='debt',
        ),
        migrations.RemoveField(
            model_name='debtcharge',
            name='account',
        ),
        migrations.RemoveField(
            model_name='debtcharge',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='debtitem',
            name='debtor',
        ),
        migrations.RemoveField(
            model_name='debtitem',
            name='origin_subaccount',
        ),
        migrations.AlterUniqueTogether(
            name='debtor',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='debtor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='splitruleitem',
            name='debtor',
        ),
        migrations.RemoveField(
            model_name='debtpayment',
            name='account',
        ),
        migrations.RemoveField(
            model_name='debtpayment',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='splitrule',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='split_rule',
        ),
        migrations.RemoveField(
            model_name='splitruleitem',
            name='template',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='shared_amount',
        ),
        migrations.DeleteModel(
            name='Debt',
        ),
        migrations.DeleteModel(
            name='DebtCharge',
        ),
        migrations.DeleteModel(
            name='DebtItem',
        ),
        migrations.DeleteModel(
            name='Debtor',
        ),
        migrations.DeleteModel(
            name='DebtPayment',
        ),
        migrations.DeleteModel(
            name='SplitRule',
        ),
        migrations.DeleteModel(
            name='SplitRuleItem',
        ),
    ]
