# Generated by Django 6.0.4 on 2026-06-14 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_remove_debtpayment_debt_remove_asset_linked_debt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributiontemplate',
            name='fallback_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fallback_templates', to='core.category'),
        ),
        migrations.AddField(
            model_name='distributiontemplate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='distributiontemplate',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='distributiontemplate',
            name='trigger_payee',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
