# Generated by Django 6.0.4 on 2026-06-17 14:23

from django.db import migrations


def migrate_to_double_entry(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Account = apps.get_model('core', 'Account')
    Category = apps.get_model('core', 'Category')
    Transaction = apps.get_model('core', 'Transaction')
    LedgerAccount = apps.get_model('core', 'LedgerAccount')
    JournalEntry = apps.get_model('core', 'JournalEntry')
    LedgerPosting = apps.get_model('core', 'LedgerPosting')

    # Step 1: Create system accounts per user
    for user in User.objects.all():
        system_income, _ = LedgerAccount.objects.get_or_create(
            user=user,
            name='System Income',
            type='INCOME',
            currency='EUR'
        )
        system_expense, _ = LedgerAccount.objects.get_or_create(
            user=user,
            name='System Expense',
            type='EXPENSE',
            currency='EUR'
        )
        cc_clearing, _ = LedgerAccount.objects.get_or_create(
            user=user,
            name='Credit Card Clearing',
            type='LIABILITY',
            currency='EUR'
        )

    # Step 2: Asset Mapping
    for account in Account.objects.all():
        LedgerAccount.objects.get_or_create(
            user=account.user,
            name=account.name,
            type='ASSET',
            currency=account.currency,
            linked_account=account
        )

    # Step 3: Shadow Claim Mapping
    for category in Category.objects.all():
        LedgerAccount.objects.get_or_create(
            user=category.user,
            name=category.name,
            type='SHADOW_CLAIM',
            currency=category.currency,
            linked_category=category
        )

    # Step 4: Transaction Translation
    # We query transactions ordered by ID or Date to make it predictable.
    for tx in Transaction.objects.all():
        # Avoid creating duplicate JournalEntry for the same legacy Transaction if re-run
        if JournalEntry.objects.filter(original_transaction=tx).exists():
            continue

        # Create JournalEntry
        je = JournalEntry.objects.create(
            user=tx.account.user,
            date=tx.date,
            description=tx.description or f"Transação {tx.id}",
            original_transaction=tx,
            created_at=tx.created_at
        )

        user = tx.account.user

        # Lookup mapped accounts
        # Source asset account (the physical account associated with legacy Transaction)
        source_ledger_acct = LedgerAccount.objects.filter(linked_account=tx.account).first()
        if not source_ledger_acct:
            # Fallback if mapping missed
            source_ledger_acct, _ = LedgerAccount.objects.get_or_create(
                user=user,
                name=tx.account.name,
                type='ASSET',
                currency=tx.account.currency,
                linked_account=tx
            )

        amount = tx.amount

        # Detect Transfer (transfer_group is filled, payee.transfer_acct is linked, or linked_transfer exists)
        is_transfer = False
        target_account = None

        if tx.payee and tx.payee.transfer_acct:
            is_transfer = True
            target_account = tx.payee.transfer_acct
        elif tx.linked_transfer:
            is_transfer = True
            target_account = tx.linked_transfer.account
        elif tx.transfer_group:
            # Try to find another transaction in the same group but different account
            sibling = Transaction.objects.filter(transfer_group=tx.transfer_group).exclude(id=tx.id).first()
            if sibling:
                is_transfer = True
                target_account = sibling.account

        if is_transfer and target_account:
            # Transfer handling
            target_ledger_acct = LedgerAccount.objects.filter(linked_account=target_account).first()
            if not target_ledger_acct:
                target_ledger_acct, _ = LedgerAccount.objects.get_or_create(
                    user=user,
                    name=target_account.name,
                    type='ASSET',
                    currency=target_account.currency,
                    linked_account=target_account
                )

            # In legacy YNAB, transfers might have positive or negative amounts depending on which side you look at.
            # We want to represent:
            # Source (where money leaves) -> Credit (CR)
            # Destination (where money enters) -> Debit (DR)
            # Typically, if amount is negative, money leaves source_ledger_acct.
            # If amount is positive, money enters source_ledger_acct.
            if amount < 0:
                abs_amount = abs(amount)
                # Leaves source, enters target
                LedgerPosting.objects.create(
                    journal_entry=je,
                    ledger_account=source_ledger_acct,
                    amount=abs_amount,
                    direction='CR',
                    status='CLEARED'
                )
                LedgerPosting.objects.create(
                    journal_entry=je,
                    ledger_account=target_ledger_acct,
                    amount=abs_amount,
                    direction='DR',
                    status='CLEARED'
                )
            else:
                # Enters source, leaves target
                LedgerPosting.objects.create(
                    journal_entry=je,
                    ledger_account=target_ledger_acct,
                    amount=amount,
                    direction='CR',
                    status='CLEARED'
                )
                LedgerPosting.objects.create(
                    journal_entry=je,
                    ledger_account=source_ledger_acct,
                    amount=amount,
                    direction='DR',
                    status='CLEARED'
                )

        elif tx.is_income:
            # Income handling: DR to asset account, CR to 'System Income'
            system_income = LedgerAccount.objects.get(user=user, type='INCOME', name='System Income')
            # Standardize negative income to positive
            abs_amount = abs(amount)
            LedgerPosting.objects.create(
                journal_entry=je,
                ledger_account=source_ledger_acct,
                amount=abs_amount,
                direction='DR',
                status='CLEARED'
            )
            LedgerPosting.objects.create(
                journal_entry=je,
                ledger_account=system_income,
                amount=abs_amount,
                direction='CR',
                status='CLEARED'
            )

        else:
            # Expense handling
            abs_amount = abs(amount)
            is_credit_card = tx.account.account_type == 'credit_card'

            if is_credit_card:
                # Credit Card Expense: DR to category (SHADOW_CLAIM), CR to 'Credit Card Clearing' (LIABILITY)
                cc_clearing = LedgerAccount.objects.get(user=user, type='LIABILITY', name='Credit Card Clearing')
                
                # Lookup or default shadow claim account
                dest_ledger_acct = None
                if tx.category:
                    dest_ledger_acct = LedgerAccount.objects.filter(linked_category=tx.category).first()
                if not dest_ledger_acct:
                    # Fallback to user's 'System Expense'
                    dest_ledger_acct = LedgerAccount.objects.get(user=user, type='EXPENSE', name='System Expense')

                LedgerPosting.objects.create(
                    journal_entry=je,
                    ledger_account=cc_clearing,
                    amount=abs_amount,
                    direction='CR',
                    status='PENDING'
                )
                LedgerPosting.objects.create(
                    journal_entry=je,
                    ledger_account=dest_ledger_acct,
                    amount=abs_amount,
                    direction='DR',
                    status='PENDING'
                )
            else:
                # Standard Expense: DR to category, CR to asset account
                dest_ledger_acct = None
                if tx.category:
                    dest_ledger_acct = LedgerAccount.objects.filter(linked_category=tx.category).first()
                if not dest_ledger_acct:
                    dest_ledger_acct = LedgerAccount.objects.get(user=user, type='EXPENSE', name='System Expense')

                LedgerPosting.objects.create(
                    journal_entry=je,
                    ledger_account=source_ledger_acct,
                    amount=abs_amount,
                    direction='CR',
                    status='CLEARED'
                )
                LedgerPosting.objects.create(
                    journal_entry=je,
                    ledger_account=dest_ledger_acct,
                    amount=abs_amount,
                    direction='DR',
                    status='CLEARED'
                )


def rollback_double_entry(apps, schema_editor):
    LedgerAccount = apps.get_model('core', 'LedgerAccount')
    JournalEntry = apps.get_model('core', 'JournalEntry')
    LedgerPosting = apps.get_model('core', 'LedgerPosting')

    LedgerPosting.objects.all().delete()
    JournalEntry.objects.all().delete()
    LedgerAccount.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_alter_account_id_alter_asset_id_alter_category_id_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_to_double_entry, rollback_double_entry),
    ]

