# Generated by Django 6.0.4 on 2026-06-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_auto_20260617_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='color',
            field=models.CharField(blank=True, help_text='Hex color for account card, e.g., #8A05BE', max_length=7, null=True),
        ),
    ]
